server:
  port: 7788
  hostname: ioa-server

tool_agent:
  image_name: sql-agent:latest
  container_name: sql-agent
  agent_type: Thing Assistant
  agent_name: SQL Query Agent
  desc: >
    This is a SQL Query Agent powered by OpenAI. It takes natural language prompts,
    understands the database schema, generates SQL queries, executes them on a database,
    and returns structured JSON results.
  port: 7070

comm:
  name: SQL Interpreter Agent
  desc: >
    This agent is responsible for interpreting natural language questions into SQL queries,
    executing them on a SQLite database, and returning structured results.
    Ideal for automated analytics, reporting, or natural language database access tasks.

  type: Thing Assistant
  max_team_up_attempts: 1
  support_nested_teams: false

  llm:
    llm_type: openai-chat
    model: gpt-4-1106-preview
    temperature: 0.1

  discussion_only: false


